<?php
declare(strict_types=1);

// Ironoc SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

IronocUtility::setRegistrar(function (IronocUtility $u): void {
    $u->clean = [IronocClean::class, 'call'];
    $u->done = [IronocDone::class, 'call'];
    $u->make_error = [IronocMakeError::class, 'call'];
    $u->feature_add = [IronocFeatureAdd::class, 'call'];
    $u->feature_hook = [IronocFeatureHook::class, 'call'];
    $u->feature_init = [IronocFeatureInit::class, 'call'];
    $u->fetcher = [IronocFetcher::class, 'call'];
    $u->make_fetch_def = [IronocMakeFetchDef::class, 'call'];
    $u->make_context = [IronocMakeContext::class, 'call'];
    $u->make_options = [IronocMakeOptions::class, 'call'];
    $u->make_request = [IronocMakeRequest::class, 'call'];
    $u->make_response = [IronocMakeResponse::class, 'call'];
    $u->make_result = [IronocMakeResult::class, 'call'];
    $u->make_point = [IronocMakePoint::class, 'call'];
    $u->make_spec = [IronocMakeSpec::class, 'call'];
    $u->make_url = [IronocMakeUrl::class, 'call'];
    $u->param = [IronocParam::class, 'call'];
    $u->prepare_auth = [IronocPrepareAuth::class, 'call'];
    $u->prepare_body = [IronocPrepareBody::class, 'call'];
    $u->prepare_headers = [IronocPrepareHeaders::class, 'call'];
    $u->prepare_method = [IronocPrepareMethod::class, 'call'];
    $u->prepare_params = [IronocPrepareParams::class, 'call'];
    $u->prepare_path = [IronocPreparePath::class, 'call'];
    $u->prepare_query = [IronocPrepareQuery::class, 'call'];
    $u->graphql_body = [IronocGraphql::class, 'body'];
    $u->graphql_errors = [IronocGraphql::class, 'errors'];
    $u->result_basic = [IronocResultBasic::class, 'call'];
    $u->result_body = [IronocResultBody::class, 'call'];
    $u->result_headers = [IronocResultHeaders::class, 'call'];
    $u->transform_request = [IronocTransformRequest::class, 'call'];
    $u->transform_response = [IronocTransformResponse::class, 'call'];
});
